server:
  port: ${APP_PORT:8080}

spring:
  application:
    name: ${APP_NAME:weborder}
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/weborderdatabase?useSSL=false&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      auto-commit: false
      connection-timeout: 3000
      validation-timeout: 3000
      max-lifetime: 60000
      minimum-idle: 1
